### ISSUE TITLE
Unable to customize a element

### ISSUE THREAD

**Issue by solominsn** [veelenga/ember-mail-to#1]
Hello,
Thank you for component. Looks great. But I have few comments:

1. Why do you create sub <a> element? Every ember component is `<div>`, so it creates unneeded element.

2. Current solution don't allow change style of the link. I'd like to write:
```html
<MailTo  @to='to@gmail.com' class="icon-email"/>
```
But it would not work because style will be added to `<div>` instead of `<a>`.

So my suggestion is to refactor component to have `link-to` helper behavior.

**Comment by veelenga** [comment]
@solominsn hi, thanks for the heads up. Yes, you are right. I think we can just remove the wrapper element using `tagName: ''` and will solve both comments. Do you agree?

**Comment by solominsn** [comment]
Yes, I think so. Seems html attributes binding will be also required (like ember guide [example](https://guides.emberjs.com/release/components/customizing-a-components-element/#toc_customizing-attributes)).

**Comment by veelenga** [comment]
I have just published 0.1.1 which allows you passing a `class` to the `a` element.
